=== energywebfoundation/elia-energyblocks-vcs/credentials/2023-nest-project/contract/schemas/contract-schema.json
{
  "type": "object",
  "properties": {
    "applicationLaw": {
      "type": "string"
    },
    "jurisdiction": {
      "type": "string"
    },
    "compensationOfTheOffer": {
      "type": "string"
    },
    "expressionOfTheOffer": {
      "type": "string"
    },
    "party2": {
      "$ref": "http://www.w3.org/2000/01/rdf-schema#Resource"
    },
    "party1": {
      "$ref": "http://www.w3.org/2000/01/rdf-schema#Resource"
    },
    "contractedItem": {
      "$ref": "https://vc-context.elia.be/2022/v1/Device"
    }
  },
  "$id": "https://vc-context.elia.be/2022/v1/Contract",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Contract"
}

=== energywebfoundation/elia-energyblocks-vcs/credentials/2023-nest-project/contract-credential/contract-context.json
[
  {
    "applicationLaw": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/applicationLaw",
    "compensationOfTheOffer": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/compensationOfTheOffer",
    "contractedItem": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/contractedItem",
    "expressionOfTheOffer": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/expressionOfTheOffer",
    "jurisdiction": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/jurisdiction",
    "party1": {
      "@id": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/party1",
      "@context": {
        "address": "https://schema.org/address",
        "brand": "https://schema.org/brand",
        "iso6523Code": "https://schema.org/iso6523Code"
      }
    },
    "party2": {
      "@id": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/party2",
      "@context": {
        "address": "https://schema.org/address",
        "familyName": "https://schema.org/familyName",
        "givenName": "https://schema.org/givenName"
      }
    }
  }
]
