=== energywebfoundation/elia-energyblocks-vcs/credentials/2023-nest-project/device-info-credential/schemas/device-schema.json
{ "type": "object", "properties": { "userConsentCapability": { "type": "string" }, "infoEndpointStandard": { "type": "string" }, "infoEndpoint": { "type": "string" }, "hardwareRevision": { "type": "string" }, "manufacturerLabel": { "type": "string" }, "manufacturerDescription": { "type": "string" }, "deviceName": { "type": "string" }, "deviceCode": { "type": "string" }, "brandName": { "type": "string" } }, "$id": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/Device", "$schema": "https://json-schema.org/draft/2020-12/schema", "title": "Device" }

=== energywebfoundation/elia-energyblocks-vcs/credentials/2023-nest-project/device-info-credential/device-info-context.json
[
  {
    "brandName": "https://saref.etsi.org/saref4ener/brandName",
    "deviceCode": "https://saref.etsi.org/saref4ener/deviceCode",
    "deviceName": "https://saref.etsi.org/saref4ener/deviceName",
    "hardwareRevision": "https://saref.etsi.org/saref4ener/hardwareRevision",
    "infoEndpoint": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/Device/infoEndpoint",
    "infoEndpointStandard": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/Device/infoEndpointStandard",
    "manufacturerDescription": "https://saref.etsi.org/saref4ener/manufacturerDescription",
    "manufacturerLabel": "https://saref.etsi.org/saref4ener/manufacturerLabel",
    "userConsentCapability": "https://github.com/energywebfoundation/elia-energyblocks-vcs/tree/master/ontology/v1/Device/userConsentCapability"
  }
]
